---
- hosts: 10.128.10.10
  tasks:
    - apt: name=libpq5 state=present
    - apt: name=redis-server state=present
    - apt: name=nginx state=present
    - apt: name=supervisor state=present

    - apt: name=python3-pkg-resources state=present
    - get_url: dest=/root/ url=http://packaging.ckan.org/python-ckan_2.9-bionic_amd64.deb
    - apt: deb=/root/python-ckan_2.9-bionic_amd64.deb state=present

    - apt: name=postgresql state=present
    - apt: name=python3-psycopg2 state=present
    - apt: name=python-psycopg2 state=present

    - postgresql_user: name=ckan_default password=password123 state=present
      no_log: true
      become: true
      become_user: postgres

    - postgresql_db: owner=ckan_default name=ckan_default encoding=utf-8
      become: true
      become_user: postgres

    - template: src=./ckan.ini.j2 dest=/etc/ckan/default/ckan.ini

    - apt: name=solr-tomcat state=present
    - template: src=./tomcat.xml.j2 dest=/etc/tomcat9/server.xml
    - file: state=link force=yes path=/etc/solr/conf/schema.xml src=/usr/lib/ckan/default/src/ckan/ckan/config/solr/schema.xml
    - systemd: name=tomcat9 state=restarted

    - apt: name=libpython2.7 state=present
    - command: ckan db init
    - command: supervisorctl reload

    - systemd:
        name: nginx
        state: restarted
